name: Publish Extension to Marketplace

on:
  push:
    branches:
      - main # or "master" or your default branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install vsce
        run: npm install -g vsce

      - name: Publish to VSCode Marketplace
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
        run: vsce publish --pat $VSCE_TOKEN
